import {describe,it,expect} from "vitest";
import {HybridExtractor,LlmExtractor} from "../src/memory/adapters/llm-extractor.js";
import {RuleBasedExtractor} from "../src/memory/adapters/rule-extractor.js";
import {OpenAIEmbeddingAdapter} from "../src/memory/adapters/openai-embedding.js";
import {LocalMemoryWorker} from "../src/memory/runtime-worker.js";
const scope={type:"workspace" as const,id:"quality"};

describe("memory semantic quality",()=>{
  it("hybrid extraction preserves rule fast paths and merges semantic proposals",async()=>{const semantic={extract:async()=>({records:[{id:"food",kind:"preference" as const,tier:"hot" as const,scope,dimension:"food",value:"用户 不喜欢吃 苹果",summary:"用户不爱吃苹果",topicIds:["food"],entityIds:[],applicability:"global" as const,strength:.9,origin:"explicit" as const,status:"active" as const,confidence:.99,sourceRefs:[],createdAt:1,updatedAt:1}],topics:[],nodes:[],edges:[]})};const result=await new HybridExtractor(new RuleBasedExtractor(),semantic).extract("<focus_user>我叫TMs，而且我不爱吃苹果</focus_user>",[],scope);expect(result.records.some((r)=>r.kind==="fact"&&(r as any).content.includes("TMs"))).toBe(true);expect(result.records.some((r)=>r.kind==="preference"&&(r as any).value.includes("苹果"))).toBe(true);});
  it("does not send one-off task requests to semantic extraction",async()=>{let calls=0;const semantic={extract:async()=>{calls++;return{records:[{id:"bad",kind:"episode" as const,tier:"hot" as const,scope,title:"task",content:"stored task",summary:"stored task",topicIds:["task"],entityIds:[],status:"active" as const,confidence:1,importance:1,sourceRefs:[],createdAt:1,updatedAt:1}],topics:[],nodes:[],edges:[]}}};const result=await new HybridExtractor(new RuleBasedExtractor(),semantic).extract("<focus_user>请检查 /opt/tagent-core 是否最新，并排查记忆数据库</focus_user>",[],scope);expect(calls).toBe(0);expect(result.records).toEqual([]);});
  it("extracts explicit Chinese food preferences in the deterministic safety path",async()=>{const extractor=new RuleBasedExtractor();const first=await extractor.extract("user: 我爱吃西瓜，我有个朋友卢鹏程也爱吃西瓜",[],scope);const values=first.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("用户 喜欢吃 西瓜");expect(values).toContain("卢鹏程 喜欢吃 西瓜");const second=await extractor.extract("user: 我不爱吃苹果",[],scope);expect((second.records[0] as any).value).toContain("不喜欢吃 苹果");});
  it("uses prior turns only for Chinese pronoun resolution",async()=>{const extractor=new HybridExtractor(new RuleBasedExtractor());const result=await extractor.extract("<context>user: 我爱吃西瓜，我有个朋友卢鹏程也是</context><focus_user>他说苹果也很好吃但是我不爱吃</focus_user>",[],scope);const values=result.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("卢鹏程 喜欢吃 西瓜");expect(values).toContain("卢鹏程 喜欢吃 苹果");expect(values).toContain("用户 不喜欢吃 苹果");});
  it("extracts homes and cross-turn neighbor relations without relying on the LLM",async()=>{const extractor=new HybridExtractor(new RuleBasedExtractor());const first=await extractor.extract("<focus_user>Sway家在前滩</focus_user>",[],scope);expect(first.records.some((r)=>r.kind==="fact"&&(r as any).content.includes("Sway 住在 前滩"))).toBe(true);const second=await extractor.extract("<context>user: Sway家在前滩</context><focus_user>乔哲家也是</focus_user>",[],scope);expect(second.records.some((r)=>r.kind==="fact"&&(r as any).content.includes("乔哲 住在 前滩"))).toBe(true);const third=await extractor.extract("<context>user: Sway家在前滩\nassistant: 记住了：Sway 家在前滩。\nuser: 乔哲家也是</context><focus_user>他俩住隔壁</focus_user>",[],scope);expect(third.records.some((r)=>r.kind==="fact"&&(r as any).content.includes("Sway 与 乔哲是邻居"))).toBe(true);expect(third.edges.some((edge)=>edge.predicate==="neighbor_of")).toBe(true);});
    it("falls back to deterministic rules when the semantic extractor fails",async()=>{const failing={extract:async()=>{throw new Error("provider down")}};const extractor=new HybridExtractor(new RuleBasedExtractor(),failing);const result=await extractor.extract("<focus_user>我叫TMs</focus_user>",[],scope);expect(result.records).toHaveLength(1);await expect(extractor.extract("<focus_user>这是一条规则无法识别的长期事实</focus_user>",[],scope)).rejects.toThrow("provider down");});
  it("surfaces background maintenance failures",async()=>{const errors:unknown[][]=[];const original=console.error;console.error=(...args)=>errors.push(args);try{const worker=new LocalMemoryWorker({runOnce:async()=>false} as any,{promote:async()=>{throw new Error("maintenance failed")},topicCandidates:async()=>[]} as any,{consolidate:async()=>undefined} as any,{verify:async()=>undefined,cleanupStaged:async()=>undefined} as any,{subjectId:"test",scopes:[scope],purpose:"capture"},1000,1000);worker.start();await new Promise((resolve)=>setTimeout(resolve,20));await worker.stop();expect(errors.some((args)=>String(args[0]).includes("Memory maintenance tick failed"))).toBe(true);}finally{console.error=original;}});
  it("does not let slow maintenance starve capture processing",async()=>{let release!:()=>void;const maintenanceStarted=new Promise<void>((resolve)=>{release=resolve});let captured=0;const capture={runOnce:async()=>{captured++;return false}} as any;const lifecycle={promote:async()=>{await maintenanceStarted},topicCandidates:async()=>[]} as any;const worker=new LocalMemoryWorker(capture,lifecycle,{consolidate:async()=>undefined} as any,{verify:async()=>undefined,cleanupStaged:async()=>undefined} as any,{subjectId:"test",scopes:[scope],purpose:"capture"},1000,1000);const maintenance=worker.maintenanceTick();await new Promise((resolve)=>setTimeout(resolve,5));await worker.captureTick();expect(captured).toBe(1);release();await maintenance;});
    it("batches OpenAI-compatible embeddings and exposes a generation",async()=>{const original=globalThis.fetch;const calls:unknown[]=[];globalThis.fetch=async(_url,init)=>{calls.push(JSON.parse(String(init?.body)));return new Response(JSON.stringify({data:[{index:0,embedding:[1,0]},{index:1,embedding:[0,1]}]}),{status:200});};try{const adapter=new OpenAIEmbeddingAdapter({baseUrl:"https://embed.test/v1",apiKey:"secret",model:"semantic",batchSize:2,extraBody:{input_type:"passage"}});expect(await adapter.embed(["a","b"])).toEqual([[1,0],[0,1]]);expect(adapter.generation).toContain("semantic");expect(calls).toHaveLength(1);}finally{globalThis.fetch=original;}});
  it.skipIf(!process.env.TAGENT_TEST_LLM_BASE_URL)("resolves the reported Chinese food preference coreference with a live LLM",async()=>{const extractor=new LlmExtractor({baseUrl:process.env.TAGENT_TEST_LLM_BASE_URL!,apiKey:process.env.TAGENT_TEST_LLM_API_KEY!,model:process.env.TAGENT_TEST_LLM_MODEL!});const result=await extractor.extract("<context>user: 我爱吃西瓜，我有个朋友卢鹏程也是</context><focus_user>他说苹果也很好吃但是我不爱吃</focus_user>",[],scope);const values=result.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("卢鹏程");expect(values).toContain("苹果");expect(values).toMatch(/用户.*不/);},120_000);
});
