import {describe,it,expect} from "vitest";
import {HybridExtractor,LlmExtractor} from "../src/memory/adapters/llm-extractor.js";
import {RuleBasedExtractor} from "../src/memory/adapters/rule-extractor.js";
import {OpenAIEmbeddingAdapter} from "../src/memory/adapters/openai-embedding.js";
const scope={type:"workspace" as const,id:"quality"};

describe("memory semantic quality",()=>{
  it("hybrid extraction preserves rule fast paths and merges semantic proposals",async()=>{const semantic={extract:async()=>({records:[{id:"food",kind:"preference" as const,tier:"hot" as const,scope,dimension:"food",value:"用户 不喜欢吃 苹果",summary:"用户不爱吃苹果",topicIds:["food"],entityIds:[],applicability:"global" as const,strength:.9,origin:"explicit" as const,status:"active" as const,confidence:.99,sourceRefs:[],createdAt:1,updatedAt:1}],topics:[],nodes:[],edges:[]})};const result=await new HybridExtractor(new RuleBasedExtractor(),semantic).extract("<focus_user>我叫TMs，而且我不爱吃苹果</focus_user>",[],scope);expect(result.records.some((r)=>r.kind==="fact"&&(r as any).content.includes("TMs"))).toBe(true);expect(result.records.some((r)=>r.kind==="preference"&&(r as any).value.includes("苹果"))).toBe(true);});
  it("extracts explicit Chinese food preferences in the deterministic safety path",async()=>{const extractor=new RuleBasedExtractor();const first=await extractor.extract("user: 我爱吃西瓜，我有个朋友卢鹏程也爱吃西瓜",[],scope);const values=first.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("用户 喜欢吃 西瓜");expect(values).toContain("卢鹏程 喜欢吃 西瓜");const second=await extractor.extract("user: 我不爱吃苹果",[],scope);expect((second.records[0] as any).value).toContain("不喜欢吃 苹果");});
  it("uses prior turns only for Chinese pronoun resolution",async()=>{const extractor=new HybridExtractor(new RuleBasedExtractor());const result=await extractor.extract("<context>user: 我爱吃西瓜，我有个朋友卢鹏程也是</context><focus_user>他说苹果也很好吃但是我不爱吃</focus_user>",[],scope);const values=result.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("卢鹏程 喜欢吃 西瓜");expect(values).toContain("卢鹏程 喜欢吃 苹果");expect(values).toContain("用户 不喜欢吃 苹果");});
  it("falls back to deterministic rules when the semantic extractor fails",async()=>{const failing={extract:async()=>{throw new Error("provider down")}};const result=await new HybridExtractor(new RuleBasedExtractor(),failing).extract("<focus_user>我叫TMs</focus_user>",[],scope);expect(result.records).toHaveLength(1);});
  it("batches OpenAI-compatible embeddings and exposes a generation",async()=>{const original=globalThis.fetch;const calls:unknown[]=[];globalThis.fetch=async(_url,init)=>{calls.push(JSON.parse(String(init?.body)));return new Response(JSON.stringify({data:[{index:0,embedding:[1,0]},{index:1,embedding:[0,1]}]}),{status:200});};try{const adapter=new OpenAIEmbeddingAdapter({baseUrl:"https://embed.test/v1",apiKey:"secret",model:"semantic",batchSize:2,extraBody:{input_type:"passage"}});expect(await adapter.embed(["a","b"])).toEqual([[1,0],[0,1]]);expect(adapter.generation).toContain("semantic");expect(calls).toHaveLength(1);}finally{globalThis.fetch=original;}});
  it.skipIf(!process.env.TAGENT_TEST_LLM_BASE_URL)("resolves the reported Chinese food preference coreference with a live LLM",async()=>{const extractor=new LlmExtractor({baseUrl:process.env.TAGENT_TEST_LLM_BASE_URL!,apiKey:process.env.TAGENT_TEST_LLM_API_KEY!,model:process.env.TAGENT_TEST_LLM_MODEL!});const result=await extractor.extract("<context>user: 我爱吃西瓜，我有个朋友卢鹏程也是</context><focus_user>他说苹果也很好吃但是我不爱吃</focus_user>",[],scope);const values=result.records.filter((r)=>r.kind==="preference").map((r)=>(r as any).value).join("\n");expect(values).toContain("卢鹏程");expect(values).toContain("苹果");expect(values).toMatch(/用户.*不/);},120_000);
});
