import { afterEach, describe, expect, it } from "vitest";
import { Store } from "../src/store/store.js";
import { SemanticJudge } from "../src/learning/semantic-judge.js";
import { LearningService } from "../src/learning/learning-service.js";
import { WorkflowService } from "../src/learning/workflow-service.js";
import { InMemoryMemoryAdapter } from "../src/memory/adapters/in-memory.js";
import { MemoryCaptureWorker } from "../src/memory/capture-worker.js";
import { MemoryService } from "../src/memory/memory-service.js";
import { DefaultPolicyEngine } from "../src/memory/policy/policy-engine.js";
import { RuleBasedExtractor } from "../src/memory/adapters/rule-extractor.js";
import { LocalBlobStore } from "../src/memory/storage/local-blob-store.js";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

const stores:Store[]=[];afterEach(()=>stores.splice(0).forEach((store)=>store.close()));
const scope={type:"workspace" as const,id:"semantic"};
function judge(store:Store,responses:Record<string,unknown>){return new SemanticJudge({baseUrl:"https://semantic.test/v1",apiKey:"x",model:"judge",minimumConfidence:.7,request:async(prompt)=>{const task=/Return \{([^\n]+)/.test(prompt)?"":"";for(const [key,value] of Object.entries(responses))if(prompt.includes(key))return{value,inputTokens:10,outputTokens:5};throw new Error(`missing semantic fixture ${task}`);}},store);}

describe("LLM semantic governance",()=>{
 it("caches structured judgments and rejects low-confidence or invalid output",async()=>{const store=new Store(":memory:");stores.push(store);let calls=0;const semantic=new SemanticJudge({baseUrl:"x",apiKey:"x",model:"m",minimumConfidence:.8,request:async()=>{calls++;return{value:{correction:true,correctionType:"factual",targetHint:"memory",communicationPreferences:[],confidence:.95,reason:"semantic correction"}};}},store);expect((await semantic.userMessage("这和我之前说的相反",""))?.correction).toBe(true);expect((await semantic.userMessage("这和我之前说的相反",""))?.correction).toBe(true);expect(calls).toBe(1);expect(semantic.snapshot()).toMatchObject({calls:1,cacheHits:1,failures:0});const low=new SemanticJudge({baseUrl:"x",apiKey:"x",model:"low",minimumConfidence:.8,request:async()=>({value:{similar:true,confidence:.4,reason:"uncertain"}})},store);expect(await low.cluster("a","b")).toBeUndefined();expect(low.snapshot().lowConfidence).toBe(1);});

 it("uses semantic capture and quality decisions while hard safety rules still win",async()=>{const store=new Store(":memory:");stores.push(store);const adapter=new InMemoryMemoryAdapter(),policy=new DefaultPolicyEngine(adapter);const memory=new MemoryService({records:adapter,vectors:adapter,topics:adapter,graph:adapter,jobs:adapter,policy,blobs:new LocalBlobStore(await mkdtemp(path.join(tmpdir(),"semantic-memory-")))});const semantic=judge(store,{"Determine whether":{shouldCapture:true,durable:true,category:"fact",confidence:.96,reason:"stable project fact"},"Judge whether this extracted":{accept:true,confidence:.95,reason:"durable",rejectionCode:"none"}});await memory.enqueueCapture({access:{subjectId:"u",scopes:[scope],purpose:"capture"},sourceRefs:[],content:"user: 这个项目长期使用PostgreSQL作为主数据库",idempotencyKey:"semantic-capture",captureSource:{kind:"user_message",role:"user"}});await new MemoryCaptureWorker(adapter,{load:async()=>""},new RuleBasedExtractor(),policy,memory,undefined,"worker",undefined,semantic).runOnce();expect([...adapter.jobs.values()][0].status).toMatch(/completed/);expect(semantic.snapshot().calls).toBeGreaterThan(0);});

 it("detects natural correction and communication preference without keyword matching",async()=>{const store=new Store(":memory:");stores.push(store);const session=store.createSession();const semantic=judge(store,{"Semantically analyze":{correction:true,correctionType:"factual",targetHint:"previous answer",communicationPreferences:[{dimension:"verbosity",value:"简洁"}],confidence:.94,reason:"user contrasts prior answer with correct fact"}});const learning=new LearningService(store,undefined,"default",semantic);const message=store.appendMessage(session.id,"user","你前面的结论和实际情况正好相反，数据库应当是 PostgreSQL；以后回答短一些");await learning.analyzeUserMessage({subjectId:`session:${session.id}`,scopeId:session.id,messageId:message.id,content:message.content});expect(learning.listCorrections(session.id)).toHaveLength(1);expect(learning.resolveCommunicationProfile(`session:${session.id}`,[{type:"session",id:session.id}]).values.verbosity?.value).toBe("简洁");});

 it("uses semantic sample, cluster and procedure judgments to distill paraphrased workflows",async()=>{const store=new Store(":memory:");stores.push(store);const session=store.createSession();const responses={"Judge whether this run":{eligible:true,reusable:true,failureIsCounterexample:false,confidence:.94,reason:"specific verified procedure"},"Judge whether two task":{similar:true,confidence:.92,reason:"same release validation intent"},"Distill only steps":{commonSteps:[{instruction:"Run the full test suite",supportRunIds:[]}],verificationChecks:["tests"],failureHandling:"Stop on test failure and preserve evidence.",confidence:.95,reason:"shared verified step"}};const semantic=judge(store,responses);const workflows=new WorkflowService(store,"",undefined,semantic);const runs=[];for(const [signature,summary] of [["发布前验证版本","1. 运行全量测试\n2. 构建发布包"],["validate build before shipping","1. Execute the complete test suite\n2. package the release"]]){const run=store.createRun(session.id,signature);runs.push(run.id);workflows.recordExperience({scopeId:session.id,runId:run.id,attempt:1,sourceType:"task_experience",taskSignature:signature,procedureSummary:summary,checksPassed:["tests"]});}(responses["Distill only steps"] as any).commonSteps[0].supportRunIds=runs;const result=await workflows.distillRepeatedExperience(session.id,"发布前验证版本");expect(result?.revision?.steps[0].instruction).toBe("Run the full test suite");expect(result?.revision?.verification[0].check).toBe("tests");});
});
