import {afterEach,describe,expect,it} from "vitest";
import {Store} from "../src/store/store.js";import {WorkflowService} from "../src/learning/workflow-service.js";import {AgentService} from "../src/core/agent-service.js";import {createApp} from "../src/app.js";
const stores:Store[]=[];afterEach(()=>stores.splice(0).forEach(s=>s.close()));
describe("learning boundary matrix",()=>{
 it.each([
  ["run.completed","completed"],["run.blocked","blocked"],["run.cancelled","cancelled"],["run.failed","failed"],
 ] as const)("projects %s idempotently",(lifecycle,outcome)=>{const store=new Store(":memory:");stores.push(store);const service=new WorkflowService(store);const session=store.createSession();const run=store.createRun(session.id,lifecycle);store.transitionRun(run.id,["running"],outcome,lifecycle,{reason:lifecycle},lifecycle,1);service.drainProjectionOutbox();service.drainProjectionOutbox();expect(store.db.prepare("SELECT lifecycle,outcome,COUNT(*) count FROM experience_observations WHERE run_id=?").get(run.id)).toEqual({lifecycle,outcome,count:1});});
 it("projects waiting_input and restart interruption",()=>{const store=new Store(":memory:");stores.push(store);const session=store.createSession();const waiting=store.createRun(session.id,"wait");store.requestUserInput(waiting.id,"need value",[{key:"v",label:"Value",description:"",inputType:"text",required:true,placeholder:""}]);const interrupted=store.createRun(session.id,"interrupt");store.markInterrupted();const service=new WorkflowService(store);service.drainProjectionOutbox();expect(store.db.prepare("SELECT lifecycle FROM experience_observations WHERE run_id=?").get(waiting.id)).toEqual({lifecycle:"run.waiting_input"});expect(store.db.prepare("SELECT lifecycle FROM experience_observations WHERE run_id=?").get(interrupted.id)).toEqual({lifecycle:"restart.interruption"});});
 it("rejects sessions:write permission bypass for teach and activation",async()=>{const store=new Store(":memory:");stores.push(store);const agent=new AgentService(store,process.cwd());const app=createApp({store,service:agent,logger:false,webRoot:process.cwd(),serviceCredentials:[{token:"session-token",scopes:["sessions:write"]},{token:"govern-token",scopes:["workflows:govern"]}]});const session=store.createSession();const teach=await app.inject({method:"POST",url:`/api/sessions/${session.id}/workflows/teach`,headers:{authorization:"Bearer session-token"},payload:{spec:{name:"x",intent:"x",cueTerms:["x"],applicability:["x"],nonApplicability:[],preconditions:[],inputContract:[],outputContract:[],steps:[{stepId:"x",instruction:"x",required:true}],verification:[],requiredCapabilities:[],riskClass:"low"}}});expect(teach.statusCode).toBe(403);const activate=await app.inject({method:"POST",url:"/api/workflows/missing/activate",headers:{authorization:"Bearer session-token"},payload:{}});expect(activate.statusCode).toBe(403);const governanceBypass=await app.inject({method:"POST",url:"/api/workflows/missing/activate",headers:{authorization:"Bearer govern-token"},payload:{approvalId:"empty"}});expect(governanceBypass.statusCode).toBe(403);const approveBypass=await app.inject({method:"POST",url:"/api/autonomy-approvals/missing/approve",headers:{authorization:"Bearer govern-token"},payload:{}});expect(approveBypass.statusCode).toBe(403);await app.close();});
});
