import {afterEach,describe,expect,it} from "vitest";
import {Store} from "../src/store/store.js";import {WorkflowService} from "../src/learning/workflow-service.js";import {AgentService} from "../src/core/agent-service.js";import {createApp} from "../src/app.js";
const stores:Store[]=[];afterEach(()=>stores.splice(0).forEach(s=>s.close()));
describe("learning boundary matrix",()=>{
 it.each([
  ["run.completed","completed"],["run.blocked","blocked"],["run.cancelled","cancelled"],["run.failed","failed"],
 ] as const)("projects %s idempotently",(lifecycle,outcome)=>{const store=new Store(":memory:");stores.push(store);const service=new WorkflowService(store);const session=store.createSession();const run=store.createRun(session.id,lifecycle);store.transitionRun(run.id,["running"],outcome,lifecycle,{reason:lifecycle},lifecycle,1);service.drainProjectionOutbox();service.drainProjectionOutbox();expect(store.db.prepare("SELECT lifecycle,outcome,COUNT(*) count FROM experience_observations WHERE run_id=?").get(run.id)).toEqual({lifecycle,outcome,count:1});});
 it("projects an immutable attempt snapshot after the Run advances",()=>{const store=new Store(":memory:");stores.push(store);const session=store.createSession();const run=store.createRun(session.id,"attempt snapshot");store.upsertPlanItem(run.id,{key:"attempt-one",title:"Attempt one step",status:"done",required:true,position:1});store.upsertCheck(run.id,{key:"attempt-one-check",title:"Attempt one check",status:"passed",required:true,command:"",evidence:"fresh",stale:false});store.recordModelUsage(run.id,"agent","attempt-one-model",{input:10,output:5,totalTokens:15,cost:0.1});store.recordContextManifest({id:"manifest-a1",runId:run.id,attempt:1,source:"session",items:[{kind:"workflow_revision",sourceId:"revision-a1",selected:true,reason:"attempt one",estimatedTokens:1}],stats:{},manifestHash:"hash-a1",createdAt:1});store.transitionRun(run.id,["running"],"completed","run.completed",{},"",1);store.db.prepare("UPDATE runs SET status='running',attempt=2,completed_at=NULL WHERE id=?").run(run.id);store.recordModelUsage(run.id,"agent","attempt-two-model",{input:100,output:50,totalTokens:150,cost:1});store.upsertPlanItem(run.id,{key:"attempt-two",title:"Attempt two step",status:"done",required:true,position:2});store.upsertCheck(run.id,{key:"attempt-one-check",title:"Attempt one check",status:"failed",required:true,command:"",evidence:"changed",stale:false});store.recordContextManifest({id:"manifest-a2",runId:run.id,attempt:2,source:"session",items:[{kind:"workflow_revision",sourceId:"revision-a2",selected:true,reason:"attempt two",estimatedTokens:1}],stats:{},manifestHash:"hash-a2",createdAt:2});const service=new WorkflowService(store);service.drainProjectionOutbox();const observation=store.db.prepare("SELECT procedure_summary as summary,checks_passed_json as checks FROM experience_observations WHERE run_id=? AND attempt=1").get(run.id) as any;expect(observation.summary).toContain("Attempt one step");expect(observation.summary).not.toContain("Attempt two step");expect(JSON.parse(observation.checks)).toEqual(["attempt-one-check"]);const outbox=store.db.prepare("SELECT snapshot_json as snapshot FROM learning_projection_outbox WHERE run_id=? AND attempt=1").get(run.id) as any;const snapshot=JSON.parse(outbox.snapshot);expect(snapshot).toMatchObject({attempt:1,status:"completed",usage:{input:10,output:5,totalTokens:15,cost:0.1}});expect(snapshot.supervision.latestContextManifest.id).toBe("manifest-a1");expect(snapshot.plan.map((item:any)=>item.key)).toEqual(["attempt-one"]);expect(snapshot.checks).toEqual([expect.objectContaining({key:"attempt-one-check",status:"passed",evidence:"fresh"})]);});
 it("projects waiting_input and restart interruption",()=>{const store=new Store(":memory:");stores.push(store);const session=store.createSession();const waiting=store.createRun(session.id,"wait");store.requestUserInput(waiting.id,"need value",[{key:"v",label:"Value",description:"",inputType:"text",required:true,placeholder:""}]);const interrupted=store.createRun(session.id,"interrupt");store.markInterrupted();const service=new WorkflowService(store);service.drainProjectionOutbox();expect(store.db.prepare("SELECT lifecycle FROM experience_observations WHERE run_id=?").get(waiting.id)).toEqual({lifecycle:"run.waiting_input"});expect(store.db.prepare("SELECT lifecycle FROM experience_observations WHERE run_id=?").get(interrupted.id)).toEqual({lifecycle:"restart.interruption"});});
 it("rejects sessions:write permission bypass for teach and activation",async()=>{const store=new Store(":memory:");stores.push(store);const agent=new AgentService(store,process.cwd());const app=createApp({store,service:agent,logger:false,webRoot:process.cwd(),serviceCredentials:[{token:"session-token",scopes:["sessions:write"]},{token:"govern-token",scopes:["workflows:govern"]}]});const session=store.createSession();const teach=await app.inject({method:"POST",url:`/api/sessions/${session.id}/workflows/teach`,headers:{authorization:"Bearer session-token"},payload:{spec:{name:"x",intent:"x",cueTerms:["x"],applicability:["x"],nonApplicability:[],preconditions:[],inputContract:[],outputContract:[],steps:[{stepId:"x",instruction:"x",required:true}],verification:[],requiredCapabilities:[],riskClass:"low"}}});expect(teach.statusCode).toBe(403);const activate=await app.inject({method:"POST",url:"/api/workflows/missing/activate",headers:{authorization:"Bearer session-token"},payload:{}});expect(activate.statusCode).toBe(403);const governanceBypass=await app.inject({method:"POST",url:"/api/workflows/missing/activate",headers:{authorization:"Bearer govern-token"},payload:{approvalId:"empty"}});expect(governanceBypass.statusCode).toBe(403);const approveBypass=await app.inject({method:"POST",url:"/api/autonomy-approvals/missing/approve",headers:{authorization:"Bearer govern-token"},payload:{}});expect(approveBypass.statusCode).toBe(403);await app.close();});
});
