import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, BrainCircuit, Check, Database, Flame, Plus, RefreshCw, Search, ShieldCheck, Snowflake, ThumbsDown, ThumbsUp, Trash2, X } from "lucide-react";
import { api, type CaptureJob, type ColdTopic, type MemoryKind, type MemoryScope, type MemoryStatusResult, type PreferenceRecord, type RecallResult, type ReindexJob, type RuntimeStatus, type WarmMemory, type CoreMemorySnapshot } from "./api";
import { Markdown } from "./LazyMarkdown";

const kinds: Array<{ value: "all" | MemoryKind; label: string }> = [{ value: "all", label: "All" }, { value: "fact", label: "Facts" }, { value: "preference", label: "Preferences" }, { value: "episode", label: "Episodes" }, { value: "procedure", label: "Procedures" }];
const formatDate = (value: number) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(value);
const memoryTitle = (record: WarmMemory) => record.kind === "preference" ? record.dimension : record.title;
const memoryContent = (record: WarmMemory) => record.kind === "preference" ? record.value : record.content;
const memorySignal = (record: WarmMemory) => record.kind === "preference" ? record.strength : record.importance;

export function MemoryPanel({ runtime, onClose }: { runtime: RuntimeStatus; onClose: () => void }) {
  const scope = useMemo<MemoryScope>(() => ({ type: "workspace", id: runtime.memoryWorkspaceScopeId ?? "default" }), [runtime.memoryWorkspaceScopeId]);
  const [status, setStatus] = useState<MemoryStatusResult | null>(null);
  const [records, setRecords] = useState<WarmMemory[]>([]);
  const [topics, setTopics] = useState<ColdTopic[]>([]);
  const [jobs,setJobs]=useState<CaptureJob[]>([]); const [reindexJobs,setReindexJobs]=useState<ReindexJob[]>([]); const [core,setCore]=useState<CoreMemorySnapshot|null>(null); const [coreText,setCoreText]=useState("");
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState<"all" | MemoryKind>("all");
  const [results, setResults] = useState<RecallResult | null>(null);
  const [selectedRecord, setSelectedRecord] = useState<WarmMemory | null>(null);
  const [selectedTopic, setSelectedTopic] = useState<ColdTopic | null>(null);
  const [captureOpen, setCaptureOpen] = useState(false);
  const [captureText, setCaptureText] = useState("");
  const [busy, setBusy] = useState(true);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const refresh = useCallback(async () => {
    setBusy(true); setError("");
    try {
      const [nextStatus, snapshot,nextJobs,nextReindex,nextCore] = await Promise.all([api.memoryStatus(scope), api.memoryExport(scope),api.memoryJobs(scope),api.memoryReindexJobs(scope),api.memoryCoreSnapshot(scope)]);
      setStatus(nextStatus); setRecords(snapshot.records); setTopics(snapshot.topics); setJobs(nextJobs);setReindexJobs(nextReindex);setCore(nextCore);setCoreText(nextCore?.markdown??"");
      setSelectedRecord((current) => current ? snapshot.records.find((item) => item.id === current.id) ?? null : null);
      setSelectedTopic((current) => current ? snapshot.topics.find((item) => item.descriptor.topicId === current.descriptor.topicId) ?? null : null);
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); }
    finally { setBusy(false); }
  }, [scope]);
  useEffect(() => { void refresh(); }, [refresh]);

  const filteredRecords = useMemo(() => { const needle = query.trim().toLowerCase(); return records.filter((record) => (kind === "all" || record.kind === kind) && (!needle || `${memoryTitle(record)} ${memoryContent(record)} ${record.summary} ${record.topicIds.join(" ")}`.toLowerCase().includes(needle))); }, [records, query, kind]);
  const filteredTopics = useMemo(() => { const needle = query.trim().toLowerCase(); return topics.filter((topic) => (kind === "all" || topic.descriptor.kind === kind) && (!needle || `${topic.descriptor.title} ${topic.descriptor.description} ${topic.body}`.toLowerCase().includes(needle))); }, [topics, query, kind]);

  async function searchMemory() { const cue = query.trim(); if (!cue) { setResults(null); return; } setBusy(true); setError(""); try { setResults(await api.memoryRecall(scope, cue, kind === "all" ? undefined : [kind])); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  async function capture() { if (!captureText.trim()) return; setBusy(true); setError(""); setMessage(""); try { await api.memoryCapture(scope, captureText.trim()); setCaptureText(""); setCaptureOpen(false); setMessage("Memory queued. Policy gates and the lifecycle worker will process it shortly."); window.setTimeout(() => void refresh(), 1400); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  async function forgetRecord(record: WarmMemory) { if (!window.confirm(`Forget “${memoryTitle(record)}”?`)) return; setBusy(true); try { await api.memoryForget(scope, [record.id]); setSelectedRecord(null); setMessage("Memory forgotten."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  async function govern(record:WarmMemory,action:"approve"|"reject"|"resolve"){setBusy(true);try{await api.memoryGovern(scope,record.id,action,{resolution:action==="resolve"?"accept":undefined});setMessage(`Memory ${action}d.`);await refresh();}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}} async function feedback(record:WarmMemory,signal:"helpful"|"harmful"){setBusy(true);try{await api.memoryFeedback(scope,record.id,signal);setMessage("Recall feedback recorded.");}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}} async function runReindex(){setBusy(true);try{await api.memoryReindex(scope);setMessage("Durable reindex queued.");window.setTimeout(()=>void refresh(),1000);}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}} async function saveCore(){setBusy(true);try{const next=await api.memoryCoreSnapshot(scope,{markdown:coreText});setCore(next);setMessage("Core Memory projection saved.");}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}} async function forgetTopic(topic: ColdTopic) { if (!window.confirm(`Forget the Cold topic “${topic.descriptor.title}”?`)) return; setBusy(true); try { await api.memoryForget(scope, undefined, [topic.descriptor.topicId]); setSelectedTopic(null); setMessage("Cold topic tombstoned; revisions remain restorable during grace period."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }

  return <div className="memory-overlay" role="dialog" aria-modal="true" aria-label="Memory center"><button className="memory-backdrop" onClick={onClose} aria-label="Close memory center" /><section className="memory-center">
    <header className="memory-header"><div className="memory-heading-icon"><BrainCircuit size={21} /></div><div><span className="eyebrow">Long-term memory</span><h2>Memory center</h2><p>Inspect recall, memory tiers, provenance and canonical topics.</p></div><div className="memory-header-actions"><span className="memory-live"><span />Enabled</span><button className="icon-button" onClick={() => void refresh()} aria-label="Refresh memory"><RefreshCw size={17} className={busy ? "spin" : ""} /></button><button className="icon-button" onClick={onClose} aria-label="Close memory center"><X size={18} /></button></div></header>
    <div className="memory-toolbar"><form className="memory-search" onSubmit={(event) => { event.preventDefault(); void searchMemory(); }}><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search facts, preferences, episodes, procedures or topics" /><button type="submit">Recall</button></form><button onClick={()=>void runReindex()}><RefreshCw size={14}/> Reindex</button><button className="memory-primary" onClick={() => setCaptureOpen(true)}><Plus size={16} />Add memory</button></div>
    {error && <div className="memory-alert error">{error}</div>}{message && <div className="memory-alert success">{message}</div>}
    <div className="memory-content"><aside className="memory-summary"><section className="memory-scope-card"><span>Active scope</span><strong>{scope.id}</strong><small>{runtime.memoryBackend ?? "memory"} metadata · {runtime.memoryColdBackend ?? "local"} Cold</small></section><div className="memory-tier-grid"><div><Flame size={16} /><span>Hot</span><strong>{status?.records.hot ?? 0}</strong><small>active cues</small></div><div><Database size={16} /><span>Warm</span><strong>{status?.records.warm ?? 0}</strong><small>searchable cards</small></div><div><Snowflake size={16} /><span>Cold</span><strong>{status?.coldTopics ?? 0}</strong><small>full pages</small></div></div><section className="memory-health-card"><div><ShieldCheck size={16} /><strong>Policy protected</strong></div><p>Sensitive data is gated before capture, embedding, storage and injection.</p><dl><div><dt>Active</dt><dd>{status?.records.active ?? 0}</dd></div><div><dt>Candidate</dt><dd>{status?.records.candidate ?? 0}</dd></div><div><dt>Disputed</dt><dd>{status?.records.disputed ?? 0}</dd></div><div><dt>Topics</dt><dd>{status?.topics ?? 0}</dd></div></dl></section><nav className="memory-kind-filter">{kinds.map((item) => <button key={item.value} className={kind === item.value ? "active" : ""} onClick={() => setKind(item.value)}>{item.label}<span>{item.value === "all" ? records.length + topics.length : records.filter((record) => record.kind === item.value).length + topics.filter((topic) => topic.descriptor.kind === item.value).length}</span></button>)}</nav></aside>
      <main className="memory-browser">{results && <section className="recall-results"><div className="memory-section-heading"><div><span className="eyebrow">Dynamic recall</span><h3>Results for “{query.trim()}”</h3></div><button onClick={() => setResults(null)}>Clear</button></div><div className="recall-grid">{results.cards.map((card) => <button key={card.id} onClick={() => setSelectedRecord(records.find((record) => record.id === card.id) ?? null)}><span className={`memory-kind ${card.kind}`}>{card.kind}</span><strong>{card.title}</strong><p>{card.content}</p><small>{card.tier} · {Math.round(card.confidence * 100)}% confidence</small></button>)}{results.coldTopics.map((topic) => <button key={topic.descriptor.topicId} onClick={() => setSelectedTopic(topic)}><span className="memory-kind cold">cold topic</span><strong>{topic.descriptor.title}</strong><p>{topic.descriptor.description}</p><small>revision {topic.revision.revision} · full page</small></button>)}</div><p className="recall-trace">{results.trace.candidateCount} candidates · {results.trace.topicIds.length} Cold route(s) · {results.trace.deniedCount} denied</p></section>}
        <section className="memory-list-section memory-core"><div className="memory-section-heading"><div><span className="eyebrow">Stable injection</span><h3>Core Memory Snapshot</h3></div><small>{core?`revision ${core.revision} · ${core.tokenCount} tokens`:"not generated"}</small></div><textarea value={coreText} onChange={event=>setCoreText(event.target.value)} rows={10} placeholder="# Core Memory"/><div className="memory-inline-actions"><button onClick={()=>void api.memoryCoreSnapshot(scope,{generate:true}).then(()=>refresh())}>Generate</button><button className="memory-primary" onClick={()=>void saveCore()}>Save projection</button></div></section>
        <section className="memory-list-section"><div className="memory-section-heading"><div><span className="eyebrow">Durable embeddings</span><h3>Reindex jobs</h3></div><small>{reindexJobs.length} jobs</small></div><div className="memory-record-list">{reindexJobs.slice(0,6).map(job=><div key={job.id} className="memory-job-row"><div><span className={`memory-kind ${job.status==="active"?"fact":"procedure"}`}>{job.status}</span><strong>{job.generation}</strong><small>{job.checkpoint.phase} · {job.checkpoint.processed}/{job.checkpoint.total??"?"} · {job.checkpoint.indexed} indexed · {job.checkpoint.skipped} skipped</small></div></div>)}</div></section>
        <section className="memory-list-section"><div className="memory-section-heading"><div><span className="eyebrow">Capture observability</span><h3>Recent jobs</h3></div><small>{jobs.length} jobs</small></div><div className="memory-record-list">{jobs.slice(0,12).map((job)=><div key={job.id} className="memory-job-row"><div><span className={`memory-kind ${job.status==="completed"?"fact":job.status==="completed_empty"?"episode":"procedure"}`}>{job.status}</span><strong>{job.request.sourceRefs.map((source)=>`${source.sourceType}:${source.sourceId}`).join(", ")||"manual capture"}</strong><small>{job.attempts} attempt(s) · {job.proposalCount??0} proposed · {job.persistedCount??0} persisted{job.errorCode?` · ${job.errorCode}`:""}</small></div></div>)}</div></section>
        <section className="memory-list-section"><div className="memory-section-heading"><div><span className="eyebrow">Hot + Warm</span><h3>Memory cards</h3></div><small>{filteredRecords.length} shown</small></div>{!filteredRecords.length ? <div className="memory-empty"><BrainCircuit size={22} /><strong>No matching memory cards</strong><p>Captured memories appear here after passing policy gates.</p></div> : <div className="memory-record-list">{filteredRecords.map((record) => <button key={record.id} onClick={() => { setSelectedTopic(null); setSelectedRecord(record); }} className={selectedRecord?.id === record.id ? "active" : ""}><span className={`tier-dot ${record.tier}`} /><div><span className={`memory-kind ${record.kind}`}>{record.kind}</span><strong>{memoryTitle(record)}</strong><p>{memoryContent(record)}</p><small>{record.tier} · {record.status} · {formatDate(record.updatedAt)}</small></div><span className="memory-confidence">{Math.round(record.confidence * 100)}%</span></button>)}</div>}</section>
        <section className="memory-list-section cold-section"><div className="memory-section-heading"><div><span className="eyebrow">Cold archive</span><h3>Canonical topic pages</h3></div><small>{filteredTopics.length} full pages</small></div>{!filteredTopics.length ? <div className="memory-empty compact"><Archive size={20} /><strong>No matching Cold topics</strong><p>Stable Warm memories consolidate into complete local Markdown pages.</p></div> : <div className="topic-grid">{filteredTopics.map((topic) => <button key={topic.descriptor.topicId} onClick={() => { setSelectedRecord(null); setSelectedTopic(topic); }} className={selectedTopic?.descriptor.topicId === topic.descriptor.topicId ? "active" : ""}><div><Snowflake size={15} /><span>{topic.descriptor.kind}</span><small>rev {topic.revision.revision}</small></div><strong>{topic.descriptor.title}</strong><p>{topic.descriptor.description}</p><footer><span>{topic.revision.tokenCount.toLocaleString()} tokens</span><span>{formatDate(topic.revision.publishedAt ?? topic.revision.createdAt)}</span></footer></button>)}</div>}</section></main>
      <aside className={`memory-detail ${selectedRecord || selectedTopic ? "open" : ""}`}>{!selectedRecord && !selectedTopic ? <div className="memory-detail-empty"><BrainCircuit size={24} /><strong>Select a memory</strong><p>Review provenance, confidence, topic links and Cold content.</p></div> : selectedRecord ? <RecordDetail record={selectedRecord} onForget={() => void forgetRecord(selectedRecord)} onGovern={(action)=>void govern(selectedRecord,action)} onFeedback={(signal)=>void feedback(selectedRecord,signal)} /> : selectedTopic ? <TopicDetail topic={selectedTopic} onForget={() => void forgetTopic(selectedTopic)} /> : null}</aside></div>
  </section>{captureOpen && <div className="memory-modal-wrap"><button className="memory-modal-backdrop" onClick={() => setCaptureOpen(false)} aria-label="Close add memory" /><section className="memory-modal"><header><div><span className="eyebrow">Policy-gated capture</span><h3>Add a memory cue</h3></div><button className="icon-button" onClick={() => setCaptureOpen(false)} aria-label="Close add memory"><X size={17} /></button></header><p>Write a fact, preference, event or procedure. Sensitive values are inspected before durable storage.</p><textarea autoFocus value={captureText} onChange={(event) => setCaptureText(event.target.value)} placeholder="Example: I prefer concise Chinese answers, but architecture reviews should include trade-offs." rows={7} /><footer><span><ShieldCheck size={14} />Scope: {scope.id}</span><div><button onClick={() => setCaptureOpen(false)}>Cancel</button><button className="memory-primary" onClick={() => void capture()} disabled={!captureText.trim() || busy}>Queue memory</button></div></footer></section></div>}</div>;
}

function RecordDetail({ record, onForget,onGovern,onFeedback }: { record: WarmMemory; onForget: () => void;onGovern:(action:"approve"|"reject"|"resolve")=>void;onFeedback:(signal:"helpful"|"harmful")=>void }) { return <div className="memory-detail-content"><header><span className={`memory-kind ${record.kind}`}>{record.kind}</span><button className="memory-danger" onClick={onForget}><Trash2 size={14} />Forget</button></header><div className="memory-inline-actions">{record.status==="candidate"&&<><button onClick={()=>onGovern("approve")}><Check size={13}/>Approve</button><button onClick={()=>onGovern("reject")}>Reject</button></>}{record.status==="disputed"&&<button onClick={()=>onGovern("resolve")}>Resolve</button>}<button onClick={()=>onFeedback("helpful")}><ThumbsUp size={13}/>Helpful</button><button onClick={()=>onFeedback("harmful")}><ThumbsDown size={13}/>Wrong</button></div><h3>{memoryTitle(record)}</h3><div className="memory-detail-body"><Markdown>{memoryContent(record)}</Markdown></div>{record.summary && record.summary !== memoryContent(record) && <section><span>Summary</span><p>{record.summary}</p></section>}<dl><div><dt>Tier</dt><dd>{record.tier}</dd></div><div><dt>Status</dt><dd>{record.status}</dd></div><div><dt>Confidence</dt><dd>{Math.round(record.confidence * 100)}%</dd></div><div><dt>{record.kind === "preference" ? "Strength" : "Importance"}</dt><dd>{Math.round(memorySignal(record) * 100)}%</dd></div></dl>{record.kind === "preference" && <section><span>Preference semantics</span><p>{(record as PreferenceRecord).applicability} · {(record as PreferenceRecord).origin}</p></section>}<section><span>Topic routes</span><div className="memory-tags">{record.topicIds.length ? record.topicIds.map((topic) => <code key={topic}>{topic}</code>) : <em>No topic route</em>}</div></section><section><span>Provenance</span><div className="memory-source-list">{record.sourceRefs.length ? record.sourceRefs.map((source, index) => <code key={`${source.sourceType}-${source.sourceId}-${index}`}>{source.sourceType}:{source.sourceId}</code>) : <em>No source reference</em>}</div></section><small className="memory-updated">Created {formatDate(record.createdAt)} · updated {formatDate(record.updatedAt)}</small></div>; }
function TopicDetail({ topic, onForget }: { topic: ColdTopic; onForget: () => void }) { return <div className="memory-detail-content topic-detail"><header><span className="memory-kind cold">cold · {topic.descriptor.kind}</span><button className="memory-danger" onClick={onForget}><Trash2 size={14} />Forget</button></header><h3>{topic.descriptor.title}</h3><p className="topic-description">{topic.descriptor.description}</p><dl><div><dt>Revision</dt><dd>{topic.revision.revision}</dd></div><div><dt>Tokens</dt><dd>{topic.revision.tokenCount.toLocaleString()}</dd></div><div><dt>Status</dt><dd>{topic.descriptor.status}</dd></div><div><dt>Storage</dt><dd>full page</dd></div></dl><section className="cold-document"><span>Canonical document</span><div><Markdown>{topic.body}</Markdown></div></section><section><span>Topic ID</span><code>{topic.descriptor.topicId}</code></section><small className="memory-updated">Published {formatDate(topic.revision.publishedAt ?? topic.revision.createdAt)}</small></div>; }
