import { randomUUID } from "node:crypto";
import type { AuditPort, GraphStorePort, JobQueuePort, RecordStorePort, TopicCatalogPort, VectorIndexPort } from "../ports.js";
import type { CaptureJob, CaptureRequest, ColdRevision, GraphEdge, GraphNode, MemoryKind, MemoryScope, TopicDescriptor, VectorDocument, VectorHit, WarmMemory } from "../types.js";
const scopeKey = (scope: MemoryScope) => `${scope.type}:${scope.id}`;
const allowed = (scope: MemoryScope, scopes: MemoryScope[]) => scopes.some((item) => scopeKey(item) === scopeKey(scope));
const terms = (value: string) => new Set(value.toLowerCase().split(/[^\p{L}\p{N}_-]+/u).filter(Boolean));
const textScore = (query: string, text: string) => { const q = terms(query); const t = terms(text); if (!q.size) return 0; return [...q].filter((term) => t.has(term) || text.toLowerCase().includes(term)).length / q.size; };
export class InMemoryMemoryAdapter implements RecordStorePort, VectorIndexPort, GraphStorePort, TopicCatalogPort, JobQueuePort, AuditPort {
  records = new Map<string, WarmMemory>(); vectors = new Map<string, VectorDocument>(); nodes = new Map<string, GraphNode>(); edges = new Map<string, GraphEdge>(); topics = new Map<string, TopicDescriptor>(); revisions = new Map<string, ColdRevision>(); current = new Map<string, string>(); jobs = new Map<string, CaptureJob>(); audits: Parameters<AuditPort["record"]>[0][] = [];
  async upsertRecords(records: WarmMemory[]) { for (const record of records) this.records.set(record.id, structuredClone(record)); }
  async search(query: string, scopes: MemoryScope[], kinds: MemoryKind[], limit: number) { return [...this.records.values()].filter((r) => allowed(r.scope, scopes) && kinds.includes(r.kind) && r.status === "active").map((record) => ({ record, score: textScore(query, "title" in record ? `${record.title} ${record.summary} ${record.content}` : `${record.dimension} ${record.value} ${record.summary}`) })).filter((x) => x.score > 0).sort((a,b) => b.score-a.score).slice(0,limit); }
  async getByIds(ids: string[], scopes: MemoryScope[]) { return ids.map((id) => this.records.get(id)).filter((r): r is WarmMemory => Boolean(r && allowed(r.scope, scopes) && r.status === "active")); }
  async getByTopicIds(topicIds:string[],scopes:MemoryScope[],kinds:MemoryKind[],limit:number){return [...this.records.values()].filter((r)=>allowed(r.scope,scopes)&&kinds.includes(r.kind)&&r.status==="active"&&r.topicIds.some((id)=>topicIds.includes(id))).sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,limit);}
  async list(scopes: MemoryScope[], kinds: MemoryKind[] = ["fact","preference","episode","procedure"], limit=10_000) { return [...this.records.values()].filter((r)=>allowed(r.scope,scopes)&&kinds.includes(r.kind)&&r.status!=="deleted"&&r.status!=="quarantined").sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,limit); }
  async forget(scopes: MemoryScope[], ids: string[] = [], topicIds: string[] = []) { let count=0; for (const record of this.records.values()) if (allowed(record.scope,scopes) && (!ids.length || ids.includes(record.id)) && (!topicIds.length || record.topicIds.some((id)=>topicIds.includes(id)))) { record.status="deleted"; count++; } return count; }
  async upsert(documents: VectorDocument[]) { for (const document of documents) { this.vectors.set(`${document.refType}:${document.refId}`, document); } }
  async searchVectors(vector: number[], scopes: MemoryScope[], kinds: MemoryKind[], limit: number, generation?: string): Promise<VectorHit[]> { return [...this.vectors.values()].filter((d)=>allowed(d.scope,scopes)&&kinds.includes(d.kind)&&(!generation||d.generation===generation)).map((d)=>({refType:d.refType,refId:d.refId,score:cosine(vector,d.vector)})).sort((a,b)=>b.score-a.score).slice(0,limit); }
  async remove(refIds: string[]) { for (const [key,value] of this.vectors) if(refIds.includes(value.refId)) this.vectors.delete(key); }
  async upsertNodes(nodes: GraphNode[]) { for(const node of nodes)this.nodes.set(node.id,node); } async upsertEdges(edges: GraphEdge[]){for(const edge of edges)this.edges.set(edge.id,edge);}
  async resolveEntities(cue:string,scopes:MemoryScope[],limit:number){return [...this.nodes.values()].filter((n)=>allowed(n.scope,scopes)&&textScore(cue,[n.canonicalName,...n.aliases].join(" "))>0).slice(0,limit);}
  async neighborhood(ids:string[],scopes:MemoryScope[],depth:1|2,limit:number){let frontier=new Set(ids);const found=new Map<string,GraphEdge>();for(let hop=0;hop<depth;hop++){const next=new Set<string>();for(const edge of this.edges.values())if(allowed(edge.scope,scopes)&&edge.status==="active"&&(frontier.has(edge.fromId)||frontier.has(edge.toId))){found.set(edge.id,edge);next.add(edge.fromId);next.add(edge.toId);if(found.size>=limit)break;}frontier=next;if(found.size>=limit)break;}const edges=[...found.values()].slice(0,limit);const nodeIds=new Set([...ids,...edges.flatMap((e)=>[e.fromId,e.toId])]);return{edges,nodes:[...nodeIds].map((id)=>this.nodes.get(id)).filter((n):n is GraphNode=>Boolean(n)).filter((n)=>allowed(n.scope,scopes))};}
  async upsertDescriptors(topics:TopicDescriptor[]){for(const topic of topics)this.topics.set(topic.topicId,topic);} async searchTopics(cue:string,scopes:MemoryScope[],kinds:MemoryKind[],limit:number){return [...this.topics.values()].filter((t)=>allowed(t.scope,scopes)&&kinds.includes(t.kind)&&t.status==="active").map((descriptor)=>({descriptor,score:textScore(cue,`${descriptor.title} ${descriptor.description} ${descriptor.aliases.join(" ")}`)})).filter((x)=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);}
  async getDescriptors(ids:string[],scopes:MemoryScope[]){return ids.map((id)=>this.topics.get(id)).filter((t):t is TopicDescriptor=>Boolean(t&&allowed(t.scope,scopes)));} async listDescriptors(scopes:MemoryScope[],kinds:MemoryKind[]=["fact","preference","episode","procedure"],limit=10000){return [...this.topics.values()].filter((t)=>allowed(t.scope,scopes)&&kinds.includes(t.kind)&&t.status!=="deleted"&&t.status!=="quarantined").sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,limit);} async stageRevision(r:ColdRevision){this.revisions.set(r.id,r);} async publishRevision(topicId:string,revisionId:string){const r=this.revisions.get(revisionId);if(!r||r.topicId!==topicId)throw new Error("Revision not staged");r.state="published";r.publishedAt=Date.now();this.current.set(topicId,revisionId);const t=this.topics.get(topicId);if(t)t.coldRevisionId=revisionId;} async abandonRevision(id:string){const r=this.revisions.get(id);if(r&&r.state==="staged")this.revisions.delete(id);} async listStagedRevisions(olderThan:number,limit:number){return [...this.revisions.values()].filter((r)=>r.state==="staged"&&r.createdAt<olderThan).slice(0,limit);} async getCurrentRevision(topicId:string,scopes:MemoryScope[]){const id=this.current.get(topicId);const r=id?this.revisions.get(id):undefined;return r&&allowed(r.scope,scopes)&&r.state==="published"?r:null;} async forgetTopics(ids:string[],scopes:MemoryScope[]){const result:ColdRevision[]=[];for(const id of ids){const t=this.topics.get(id);if(t&&allowed(t.scope,scopes)){t.status="deleted";const r=await this.getCurrentRevision(id,scopes);if(r)result.push(r);}}return result;}
  async enqueue(request:CaptureRequest){const existing=[...this.jobs.values()].find((j)=>j.request.idempotencyKey===request.idempotencyKey);if(existing)return existing;const now=Date.now();const job:CaptureJob={id:randomUUID(),request,status:"queued",attempts:0,createdAt:now,updatedAt:now};this.jobs.set(job.id,job);return job;} async claim(owner:string,leaseMs:number){const job=[...this.jobs.values()].find((j)=>j.status==="queued"||(j.status==="running"&&(j.leaseUntil??0)<Date.now()));if(!job)return null;job.status="running";job.attempts++;job.leaseOwner=owner;job.leaseUntil=Date.now()+leaseMs;job.updatedAt=Date.now();return structuredClone(job);} async complete(id:string,result={proposalCount:0,persistedCount:0}){const j=this.jobs.get(id);if(j){j.status=result.proposalCount===0?"completed_empty":"completed";j.proposalCount=result.proposalCount;j.persistedCount=result.persistedCount;j.errorCode=result.proposalCount===0?"zero_proposals":undefined;j.updatedAt=Date.now();}} async fail(id:string,errorCode:string,retryable:boolean){const j=this.jobs.get(id);if(j){j.status=retryable&&j.attempts<5?"queued":"dead_letter";j.errorCode=errorCode;j.updatedAt=Date.now();}}
  async listJobs(scopes:MemoryScope[],limit=100){return [...this.jobs.values()].filter((job)=>job.request.access.scopes.some((scope)=>allowed(scope,scopes))).sort((a,b)=>b.createdAt-a.createdAt).slice(0,limit);} async getJob(id:string){return this.jobs.get(id)??null;}
 async record(event:Parameters<AuditPort["record"]>[0]){this.audits.push(event);}
  // Explicit aliases avoid coupling callers to the combined test adapter.
  topicSearch(cue:string,scopes:MemoryScope[],kinds:MemoryKind[],limit:number){return this.searchTopics(cue,scopes,kinds,limit);} topicForget(ids:string[],scopes:MemoryScope[]){return this.forgetTopics(ids,scopes);} vectorSearch(vector:number[],scopes:MemoryScope[],kinds:MemoryKind[],limit:number){return this.searchVectors(vector,scopes,kinds,limit);}
}
function cosine(a:number[],b:number[]){if(a.length!==b.length||!a.length)return 0;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0;}
