import type { ExtractorPort, JobQueuePort, SourceLoaderPort } from "./ports.js";
import type { PolicyGatePort } from "./policy/policy-engine.js";
import type { MemoryService } from "./memory-service.js";
import type { MemoryLifecycle } from "./lifecycle.js";
import type { SourceReference } from "./types.js";
export class MemoryCaptureWorker {
  constructor(private readonly jobs:JobQueuePort,private readonly source:SourceLoaderPort,private readonly extractor:ExtractorPort,private readonly policy:PolicyGatePort,private readonly service:MemoryService,private readonly lifecycle?:MemoryLifecycle,private readonly owner=`memory-worker:${process.pid}`,private readonly onEvent?:(event:{type:string;sourceRefs:SourceReference[];data:Record<string,unknown>})=>void){}
  async runOnce(){const job=await this.jobs.claim(this.owner,30_000);if(!job)return false;try{const scope=job.request.access.scopes[0];let content=job.request.content??"";if(!content)content=await this.source.load(job.request.access,job.request.sourceRefs);const decision=await this.policy.evaluate("source_egress",job.request.access,{text:content,scope});if(decision.action!=="allow"&&decision.action!=="transform"){await this.jobs.fail(job.id,"source_policy_rejected",false);return true;}const proposal=await this.extractor.extract(decision.payload.text,job.request.sourceRefs,scope);const integrated=this.lifecycle?await this.lifecycle.integrate(job.request.access,proposal):proposal;const persisted=await this.service.persistExtracted(job.request.access,integrated.records,integrated.topics,proposal.nodes,proposal.edges);await this.jobs.complete(job.id,{proposalCount:proposal.records.length,persistedCount:persisted.length});this.onEvent?.({type:proposal.records.length?"memory.capture.completed":"memory.capture.empty",sourceRefs:job.request.sourceRefs,data:{jobId:job.id,attempts:job.attempts,proposalCount:proposal.records.length,persistedCount:persisted.length,latencyMs:Date.now()-job.createdAt,errorCode:proposal.records.length?undefined:"zero_proposals"}});return true;}catch(error){const errorCode=error instanceof Error?error.name:"capture_error";await this.jobs.fail(job.id,errorCode,true);this.onEvent?.({type:"memory.capture.failed",sourceRefs:job.request.sourceRefs,data:{jobId:job.id,attempts:job.attempts,errorCode,latencyMs:Date.now()-job.createdAt}});return true;}}
}
