import type { MemoryService } from "./memory-service.js";
import type { RecordStorePort, TopicCatalogPort } from "./ports.js";
import type { AccessContext, TopicDescriptor, WarmMemory } from "./types.js";
import type { SemanticConsolidatorPort } from "./adapters/llm-consolidator.js";
export interface ConsolidationOptions { minimumRecords?:number; minimumConfidence?:number; maximumTopicTokens?:number }
export class MemoryConsolidator {
  constructor(private readonly records:RecordStorePort,private readonly topics:TopicCatalogPort,private readonly service:MemoryService,private readonly options:ConsolidationOptions={},private readonly semantic?:SemanticConsolidatorPort){}
  async consolidate(access:AccessContext,topicId:string){const [descriptor]=await this.topics.getDescriptors([topicId],access.scopes);if(!descriptor)return{status:"missing" as const};const records=(await this.records.list(access.scopes,[descriptor.kind],10_000)).filter((r)=>r.topicIds.includes(topicId)&&r.status==="active"&&r.confidence>=(this.options.minimumConfidence??0.65));if(records.length<(this.options.minimumRecords??1))return{status:"insufficient" as const,count:records.length};const current=await this.service.getColdTopic(access,topicId);const publishedAt=current?.revision.publishedAt;if(publishedAt&&records.every((record)=>record.updatedAt<=publishedAt))return{status:"unchanged" as const,topic:current,count:records.length};const body=this.semantic?await this.semantic.consolidate(descriptor,records,current?.body).catch(()=>renderTopic(descriptor,records,current?.body)):renderTopic(descriptor,records,current?.body);if(current?.body===body)return{status:"unchanged" as const,topic:current,count:records.length};const published=await this.service.publishColdTopic(access,descriptor,body);return{status:"published" as const,topic:published,count:records.length};}
}
function renderTopic(topic:TopicDescriptor,records:WarmMemory[],_previous?:string){const facts=records.filter((r)=>r.kind==="fact");const preferences=records.filter((r)=>r.kind==="preference");const episodes=records.filter((r)=>r.kind==="episode");const procedures=records.filter((r)=>r.kind==="procedure");return [`---`,`topic_id: ${topic.topicId}`,`kind: ${topic.kind}`,`version: 1`,`---`,`# ${topic.title}`,topic.description,section("Current Facts",facts.map(content)),section("Preferences",preferences.map(content)),section("Episodes",episodes.map(content)),section("Procedures",procedures.map(content)),`## Provenance`,...records.flatMap((r)=>r.sourceRefs.map((ref)=>`- ${ref.sourceType}:${ref.sourceId}${ref.revision?`@${ref.revision}`:""}`))].filter(Boolean).join("\n\n");}
function section(title:string,items:string[]){return items.length?`## ${title}\n\n${items.map((item)=>`- ${item}`).join("\n")}`:"";}function content(record:WarmMemory){return record.kind==="preference"?`${record.dimension}: ${record.value}`:record.content;}
