import { createHash } from "node:crypto";
import type { CoreSnapshotPort, RecordStorePort } from "./ports.js";
import { estimateTextTokens } from "./token-estimator.js";
import type { AccessContext, CoreMemorySnapshot, WarmMemory } from "./types.js";
import { isControlPlaneText, isOneOffRequest } from "./quality.js";
export class CoreMemorySnapshotService {
 constructor(private records:RecordStorePort,private snapshots:CoreSnapshotPort,private maxTokens=1800){}
 async generate(access:AccessContext){const scope=access.scopes[0],current=await this.snapshots.getSnapshot(scope);if(current?.editedAt)return current;const records=(await this.records.list([scope],undefined,50_000)).filter(coreEligible).sort((a,b)=>score(b)-score(a));const sections=new Map<string,string[]>();const ids:string[]=[];let used=0;for(const r of records){const heading=section(r),line=`- ${r.kind==="preference"?`${r.dimension}: ${r.value}`:`${r.title}: ${r.summary||r.content}`} <!-- memory:${r.id} -->`,tokens=estimateTextTokens(line);if(used+tokens>this.maxTokens)continue;(sections.get(heading)??(sections.set(heading,[]),sections.get(heading)!)).push(line);ids.push(r.id);used+=tokens;}const body=["# Core Memory","","> Generated from high-value active memory. Edit through the Memory Center so provenance and revision history remain intact.",...([...sections].flatMap(([h,lines])=>["",`## ${h}`,"",...lines]))].join("\n").trim()+"\n";if(current?.checksum===hash(body))return current;const snapshot:CoreMemorySnapshot={scope,revision:(current?.revision??0)+1,markdown:body,sourceRecordIds:ids,checksum:hash(body),tokenCount:estimateTextTokens(body),generatedAt:Date.now()};await this.snapshots.putSnapshot(snapshot);return snapshot;}
 async get(access:AccessContext){return this.snapshots.getSnapshot(access.scopes[0]);}
 async update(access:AccessContext,markdown:string){const scope=access.scopes[0],current=await this.snapshots.getSnapshot(scope);const snapshot:CoreMemorySnapshot={scope,revision:(current?.revision??0)+1,markdown,sourceRecordIds:current?.sourceRecordIds??[],checksum:hash(markdown),tokenCount:estimateTextTokens(markdown),generatedAt:Date.now(),editedAt:Date.now()};await this.snapshots.putSnapshot(snapshot);return snapshot;}
}
function score(r:WarmMemory){const trust=r.provenance?.trustLevel==="high"?1:r.provenance?.trustLevel==="medium"?.8:.6;return r.confidence*(r.kind==="preference"?r.strength:r.importance)*trust;}
function section(r:WarmMemory){if(r.kind==="preference")return "Preferences and Rules";const p=r.semantic?.predicate??"";if(/name|identity|称呼|姓名/.test(p+r.kind+("title" in r?r.title:"")))return "Identity";if(/decision|决定|规则|constraint/.test(p+("title" in r?r.title:"")))return "Decisions and Constraints";if(r.kind==="procedure")return "Environment and Procedures";return "Stable Facts";}
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");

function coreEligible(r:WarmMemory){if(r.status!=="active")return false;const text=r.kind==="preference"?`${r.dimension} ${r.value} ${r.summary}`:`${r.title} ${r.content} ${r.summary}`;if(isControlPlaneText(text)||isOneOffRequest(text)||r.kind==="episode")return false;if(r.kind==="preference")return r.origin!=="inferred"&&r.confidence>=.8;if(r.kind==="procedure")return r.provenance?.evidenceClass==="tool_verified_fact"||(r.lifecycle?.confirmationCount??1)>=2;if(r.kind==="fact"){const subject=r.semantic?.subject??"",predicate=r.semantic?.predicate??"";return /^(?:用户|我|user)$/i.test(subject)||/identity|姓名|称呼|偏好|规则|约束|决定|decision|constraint/i.test(`${r.title} ${r.content} ${r.summary} ${predicate}`)||r.provenance?.evidenceClass==="tool_verified_fact";}return false;}
