import { createHash } from "node:crypto";
import type { CoreSnapshotPort, RecordStorePort } from "./ports.js";
import { estimateTextTokens } from "./token-estimator.js";
import type { AccessContext, CoreMemorySnapshot, WarmMemory } from "./types.js";
import { isControlPlaneText, isOneOffRequest } from "./quality.js";
export class CoreMemorySnapshotService {
 private readonly queues=new Map<string,Promise<CoreMemorySnapshot>>();
 constructor(private records:RecordStorePort,private snapshots:CoreSnapshotPort,private maxTokens=1800){}
 async generate(access:AccessContext,options:{force?:boolean}={}){const scope=access.scopes[0];if(!scope)throw new Error("Core snapshot requires a scope");return this.serialize(scope,()=>this.generateUnlocked(scope,Boolean(options.force)));}
 async get(access:AccessContext){return this.snapshots.getSnapshot(access.scopes[0]);}
 async update(access:AccessContext,markdown:string){const scope=access.scopes[0];if(!scope)throw new Error("Core snapshot requires a scope");return this.serialize(scope,async()=>{for(let attempt=0;attempt<4;attempt++){const current=await this.snapshots.getSnapshot(scope),snapshot:CoreMemorySnapshot={scope,revision:(current?.revision??0)+1,markdown,sourceRecordIds:current?.sourceRecordIds??[],checksum:hash(markdown),tokenCount:estimateTextTokens(markdown),generatedAt:Date.now(),editedAt:Date.now()};if(await this.snapshots.putSnapshot(snapshot))return snapshot;}throw new Error("Core snapshot revision conflict");});}
 private async generateUnlocked(scope:CoreMemorySnapshot["scope"],force:boolean){const records=(await this.records.list([scope],undefined,50_000)).filter(isCoreMemoryEligible).sort((a,b)=>score(b)-score(a)),rendered=render(records,this.maxTokens);for(let attempt=0;attempt<4;attempt++){const current=await this.snapshots.getSnapshot(scope),body=current?.editedAt&&!force?mergeEdited(current.markdown,rendered.markdown):rendered.markdown,checksum=hash(body);if(current?.checksum===checksum&&sameIds(current.sourceRecordIds,rendered.ids))return current;const snapshot:CoreMemorySnapshot={scope,revision:(current?.revision??0)+1,markdown:body,sourceRecordIds:rendered.ids,checksum,tokenCount:estimateTextTokens(body),generatedAt:Date.now(),...(current?.editedAt&&!force?{editedAt:current.editedAt}:{})};if(await this.snapshots.putSnapshot(snapshot))return snapshot;}throw new Error("Core snapshot revision conflict");}
 private serialize(scope:CoreMemorySnapshot["scope"],operation:()=>Promise<CoreMemorySnapshot>){const key=`${scope.type}:${scope.id}`,prior=this.queues.get(key)??Promise.resolve(undefined as unknown as CoreMemorySnapshot),next=prior.catch(()=>undefined).then(operation);this.queues.set(key,next);void next.finally(()=>{if(this.queues.get(key)===next)this.queues.delete(key);}).catch(()=>undefined);return next;}
}
function score(r:WarmMemory){const trust=r.provenance?.trustLevel==="high"?1:r.provenance?.trustLevel==="medium"?.8:.6;return r.confidence*(r.kind==="preference"?r.strength:r.importance)*trust;}
function section(r:WarmMemory){if(r.kind==="preference")return "Preferences and Rules";const p=r.semantic?.predicate??"";if(/name|identity|称呼|姓名/.test(p+r.kind+("title" in r?r.title:"")))return "Identity";if(/decision|决定|规则|constraint/.test(p+("title" in r?r.title:"")))return "Decisions and Constraints";if(r.kind==="procedure")return "Environment and Procedures";return "Stable Facts";}
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");

function render(records:WarmMemory[],maxTokens:number){const sections=new Map<string,string[]>(),ids:string[]=[];let used=0;for(const r of records){const heading=section(r),line=`- ${r.kind==="preference"?`${r.dimension}: ${r.value}`:`${r.title}: ${r.summary||r.content}`} <!-- memory:${r.id} -->`,tokens=estimateTextTokens(line);if(used+tokens>maxTokens)continue;(sections.get(heading)??(sections.set(heading,[]),sections.get(heading)!)).push(line);ids.push(r.id);used+=tokens;}return{markdown:["# Core Memory","","> Generated from high-value active memory. Edit through the Memory Center so provenance and revision history remain intact.",...([...sections].flatMap(([heading,lines])=>["",`## ${heading}`,"",...lines]))].join("\n").trim()+"\n",ids};}
function mergeEdited(markdown:string,generated:string){const withoutSynced=markdown.replace(/\n?<!-- memory-sync:start -->[\s\S]*?<!-- memory-sync:end -->\n?/g,"\n"),manual=withoutSynced.split("\n").filter((line)=>!/<!--\s*memory:[^>]+-->/.test(line)).join("\n").replace(/\n{3,}/g,"\n\n").trim(),lines=generated.split("\n").filter((line)=>/<!--\s*memory:[^>]+-->/.test(line)),synced=lines.length?`<!-- memory-sync:start -->\n## Synced Memory\n\n${lines.join("\n")}\n<!-- memory-sync:end -->`:"";return[manual,synced].filter(Boolean).join("\n\n").trim()+"\n";}
function sameIds(left:string[],right:string[]){return left.length===right.length&&left.every((id,index)=>id===right[index]);}

export function isCoreMemoryEligible(r:WarmMemory){if(r.status!=="active")return false;const text=r.kind==="preference"?`${r.dimension} ${r.value} ${r.summary}`:`${r.title} ${r.content} ${r.summary}`;if(isControlPlaneText(text)||isOneOffRequest(text)||r.kind==="episode")return false;if(r.kind==="preference")return r.origin!=="inferred"&&r.confidence>=.8;if(r.kind==="procedure")return r.provenance?.evidenceClass==="tool_verified_fact"||(r.lifecycle?.confirmationCount??1)>=2;if(r.kind==="fact"){const subject=r.semantic?.subject??"",predicate=r.semantic?.predicate??"";return /^(?:用户|我|user)$/i.test(subject)||/identity|姓名|称呼|偏好|规则|约束|决定|decision|constraint/i.test(`${r.title} ${r.content} ${r.summary} ${predicate}`)||r.provenance?.evidenceClass==="tool_verified_fact";}return false;}
