import { createHash, randomUUID } from "node:crypto";
import type { EmbeddingPort, RecordStorePort, ReindexJobPort, TopicCatalogPort, VectorIndexPort } from "./ports.js";
import type { AccessContext, ReindexJob, VectorDocument } from "./types.js";
export class DurableReindexWorker {
 private running=false;
 constructor(private records:RecordStorePort,private topics:TopicCatalogPort,private vectors:VectorIndexPort,private embeddings:EmbeddingPort,private jobs:ReindexJobPort,private access:AccessContext,private batchSize=64,private leaseMs=30_000){}
 async enqueue(){return this.jobs.enqueueReindex(this.access.scopes[0],this.embeddings.generation);}
 async runOnce(owner=`reindex-${process.pid}-${randomUUID()}`){if(this.running)return false;this.running=true;try{const job=await this.jobs.claimReindex(owner,this.leaseMs);if(!job)return false;await this.process(job,owner);return true;}finally{this.running=false;}}
 private async process(job:ReindexJob,owner:string){const token=job.leaseToken!,fence=job.fencingToken,scope=[job.scope];try{const records=await this.records.list(scope,undefined,100_000),topics=await this.topics.listDescriptors(scope,undefined,100_000);const items:Omit<VectorDocument,"vector"|"generation">[]=[...records.map(r=>({refType:(r.tier==="hot"?"hot_record":"warm_record") as "hot_record"|"warm_record",refId:r.id,scope:r.scope,kind:r.kind,text:r.kind==="preference"?`${r.dimension}: ${r.value}`:`${r.title}\n${r.summary}`,contentHash:hash(r.kind==="preference"?`${r.dimension}: ${r.value}`:`${r.title}\n${r.summary}`)})),...topics.map(t=>({refType:"topic_descriptor" as const,refId:t.topicId,scope:t.scope,kind:t.kind,text:t.embeddingText,contentHash:hash(t.embeddingText)}))];job.checkpoint={...job.checkpoint,phase:"scan_records",processed:0,indexed:0,skipped:0,failed:0,total:items.length};await this.jobs.upsertGeneration({scope:job.scope,generation:job.generation,status:"staging",expected:items.length,indexed:0,skipped:0,updatedAt:Date.now()});const existing=await this.vectors.contentHashes?.(items.map(x=>({refType:x.refType,refId:x.refId,generation:job.generation})))??new Map();for(let offset=0;offset<items.length;offset+=this.batchSize){const batch=items.slice(offset,offset+this.batchSize),changed=batch.filter(x=>existing.get(`${x.refType}:${x.refId}`)!==x.contentHash);if(changed.length){const embedded=await this.embeddings.embed(changed.map(x=>x.text));await this.vectors.upsert(changed.map((x,i)=>({...x,vector:embedded[i],generation:job.generation})));}job.checkpoint={...job.checkpoint,phase:"embed",processed:Math.min(items.length,offset+batch.length),indexed:job.checkpoint.indexed+changed.length,skipped:job.checkpoint.skipped+batch.length-changed.length};if(!await this.jobs.renewReindex(job.id,owner,token,fence,this.leaseMs))throw new Error("reindex_lease_lost");if(!await this.jobs.checkpointReindex(job,owner,token,fence))throw new Error("reindex_fenced");}
 const active=new Set(items.map(x=>`${x.refType}:${x.refId}`));job.checkpoint.phase="activate";if(!await this.jobs.renewReindex(job.id,owner,token,fence,this.leaseMs))throw new Error("reindex_lease_lost");await this.vectors.removeMissing?.(job.generation,active,scope);await this.jobs.upsertGeneration({scope:job.scope,generation:job.generation,status:"ready",expected:items.length,indexed:job.checkpoint.indexed,skipped:job.checkpoint.skipped,updatedAt:Date.now()});await this.jobs.upsertGeneration({scope:job.scope,generation:job.generation,status:"active",expected:items.length,indexed:job.checkpoint.indexed,skipped:job.checkpoint.skipped,activatedAt:Date.now(),updatedAt:Date.now()});job.status="active";job.checkpoint.phase="cleanup";await this.jobs.completeReindex(job,owner,token,fence);await this.vectors.garbageCollectGenerations?.(job.generation,scope);
 }catch(error){await this.jobs.failReindex(job.id,owner,token,fence,error instanceof Error?error.message:"reindex_failed");throw error;}}
}
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
