import type { AccessContext } from "./types.js";
import type { MemoryCaptureWorker } from "./capture-worker.js";
import type { MemoryConsolidator } from "./consolidator.js";
import type { MemoryLifecycle } from "./lifecycle.js";
import type { ColdStorageReconciler } from "./reconciler.js";
import type { DurableReindexWorker } from "./reindex-worker.js";
import type { CoreMemorySnapshotService } from "./core-snapshot.js";
import type { BlobStorePort, OperationsStatePort } from "./ports.js";

export class LocalMemoryWorker {
  private captureRunning=false;private maintenanceRunning=false;private captureTimer?:ReturnType<typeof setInterval>;private maintenanceTimer?:ReturnType<typeof setInterval>;private captureTask?:Promise<boolean>;private maintenanceTask?:Promise<boolean>;
  constructor(private readonly capture:MemoryCaptureWorker,private readonly lifecycle:MemoryLifecycle,private readonly consolidator:MemoryConsolidator,private readonly reconciler:ColdStorageReconciler,private readonly access:AccessContext,private readonly captureIntervalMs:number,private readonly maintenanceIntervalMs:number,private readonly onHeartbeat?:()=>void,private readonly onConsolidation?:()=>void,private readonly reindex?:DurableReindexWorker,private readonly core?:CoreMemorySnapshotService,private readonly operations?:OperationsStatePort,private readonly blobs?:BlobStorePort){}
  start(){if(this.captureTimer)return;const capture=()=>{this.captureTask=this.captureTick().catch(error=>{console.error("Memory capture tick failed",error);return false;});};const maintenance=()=>{this.maintenanceTask=this.maintenanceTick().catch(error=>{console.error("Memory maintenance tick failed",error);return false;});};this.captureTimer=setInterval(capture,this.captureIntervalMs);this.maintenanceTimer=setInterval(maintenance,this.maintenanceIntervalMs);this.captureTimer.unref?.();this.maintenanceTimer.unref?.();capture();maintenance();}
  async stop(){if(this.captureTimer)clearInterval(this.captureTimer);if(this.maintenanceTimer)clearInterval(this.maintenanceTimer);this.captureTimer=undefined;this.maintenanceTimer=undefined;await Promise.allSettled([this.captureTask,this.maintenanceTask].filter((task):task is Promise<boolean>=>Boolean(task)));}
  async captureTick(){if(this.captureRunning)return false;this.captureRunning=true;this.onHeartbeat?.();const started=Date.now();try{let count=0;while(count<20&&await this.capture.runOnce())count++;await this.operations?.recordMetric(this.access.scopes[0],"capture_total",count,Date.now());await this.operations?.recordMetric(this.access.scopes[0],count?"capture_active_poll_total":"capture_idle_poll_total",1,Date.now());await this.operations?.recordMetric(this.access.scopes[0],"capture_latency_ms",Date.now()-started,Date.now());await this.reindex?.runOnce().catch(async error=>{await this.operations?.recordDegraded(this.access.scopes[0],`reindex:${String(error)}`,Date.now());});return count>0;}catch(error){await this.operations?.recordMetric(this.access.scopes[0],"capture_error",1,Date.now());throw error;}finally{this.captureRunning=false;}}
  async maintenanceTick(){if(this.maintenanceRunning)return false;this.maintenanceRunning=true;this.onHeartbeat?.();const started=Date.now();try{await this.lifecycle.promote(this.access);const batch=this.lifecycle.topicCandidateBatch?await this.lifecycle.topicCandidateBatch(this.access):{topics:await this.lifecycle.topicCandidates(this.access),evidence:undefined},candidates=batch.topics;for(const topic of candidates.slice(0,20))await this.consolidator.consolidate(this.access,topic.topicId,batch.evidence?{descriptor:topic,records:batch.evidence.get(topic.topicId)??[]}:undefined);await this.reconciler.verify(this.access,candidates.map(x=>x.topicId));await this.reconciler.cleanupStaged();await this.core?.generate(this.access);this.onConsolidation?.();await this.operations?.recordMetric(this.access.scopes[0],"consolidation_total",1,Date.now());await this.operations?.recordMetric(this.access.scopes[0],"consolidation_latency_ms",Date.now()-started,Date.now());return true;}catch(error){await this.operations?.recordMetric(this.access.scopes[0],"consolidation_error",1,Date.now());throw error;}finally{this.maintenanceRunning=false;}}
}
