import { useCallback, useEffect, useState, type ReactNode } from "react";
import { BrainCircuit, Check, Clock3, Eye, RefreshCw, RotateCcw, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import { api, type LearningCenterData, type WorkflowDefinition } from "./api";

const formatDate = (value: number) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(value);

export function LearningCenter({ sessionId, onClose }: { sessionId: string; onClose: () => void }) {
  const [data, setData] = useState<LearningCenterData | null>(null);
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const refresh = useCallback(async () => { setBusy(true); setError(""); try { setData(await api.learningCenter(sessionId)); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }, [sessionId]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function action(work: () => Promise<unknown>, success: string) { setBusy(true); setError(""); try { await work(); setMessage(success); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  const workflows = data?.workflows ?? [];
  return <div className="memory-overlay" role="dialog" aria-modal="true" aria-label="Learning center"><button className="memory-backdrop" onClick={onClose} aria-label="Close learning center" /><section className="memory-center learning-center">
    <header className="memory-header"><div className="memory-heading-icon"><BrainCircuit size={21} /></div><div><span className="eyebrow">Controlled evolution</span><h2>Learning center</h2><p>Govern workflows, application attribution, feedback, proposals and reversible lifecycle changes.</p></div><div className="memory-header-actions"><span className="memory-live"><span />Audited</span><button className="icon-button" onClick={() => void refresh()}><RefreshCw size={17} className={busy ? "spin" : ""} /></button><button className="icon-button" onClick={onClose}><X size={18} /></button></div></header>
    {error && <div className="memory-alert error">{error}</div>}{message && <div className="memory-alert success">{message}</div>}
    {data?.featureState && <div className={`learning-mode-banner ${data.featureState.autoExecutionEnabled?"active":"passive"}`}><ShieldCheck size={16}/><div><strong>{data.featureState.autoExecutionEnabled?"Execution participation enabled":"Passive learning mode"}</strong><span>{data.featureState.autoExecutionEnabled?"Workflow recall and approved execution paths are available. Every active action still requires a separate human approval.":"Observation, evidence capture, distillation and candidate evolution continue automatically. Workflow recall, application, activation and canary start are blocked."}</span></div><small>Memory: {data.featureState.memoryEnabled?"on":"off"}</small></div>}
    <div className="autonomy-summary"><Summary icon={<Eye size={16}/>} label="Observe & learn" value={`${data?.autonomyAudit.filter(item=>["observe","learn"].includes(item.category)).length??0}`} detail="automatic, policy bounded"/><Summary icon={<Sparkles size={16}/>} label="Distill & evolve" value={`${(data?.distillationMetrics.queued??0)+(data?.distillationMetrics.running??0)}`} detail="background candidates"/><Summary icon={<Clock3 size={16}/>} label="Awaiting approval" value={`${data?.approvals.filter(item=>item.status==="pending").length??0}`} detail="no behavior change yet"/><Summary icon={<ShieldCheck size={16}/>} label="Executed approvals" value={`${data?.approvals.filter(item=>item.status==="executed").length??0}`} detail="human authorized"/></div>
    <div className="learning-grid"><section className="learning-main"><div className="memory-section-heading"><div><span className="eyebrow">Registry</span><h3>Workflows</h3></div><small>{workflows.length} retained</small></div>
      {!workflows.length ? <div className="memory-empty"><BrainCircuit size={22}/><strong>No workflows yet</strong><p>Explicit teaching and repeated verified runs create candidates here.</p></div> : workflows.map((workflow) => <WorkflowCard key={workflow.id} workflow={workflow} onAction={action} />)}
    </section><aside className="learning-audit"><Audit title="Human approval queue" count={data?.approvals.length ?? 0}>{data?.approvals.slice(0,20).map(item=><div key={item.id} className={`approval-row ${item.status}`}><strong>{item.actionType.replaceAll("_"," ")} · {item.status}</strong><span>{item.riskClass} risk · expires {formatDate(item.expiresAt)}</span><small>{item.requestReason||"No reason"}</small><details><summary>Impact, evidence, diff & rollback</summary><pre>{JSON.stringify({impact:JSON.parse(item.impactScopeJson),evidence:JSON.parse(item.evidenceJson),diff:JSON.parse(item.diffJson),rollback:JSON.parse(item.rollbackJson)},null,2)}</pre></details>{item.status==="pending"&&<p><button onClick={()=>void action(()=>api.approveAutonomy(item.id),"Approval granted; execution is still a separate action.")}><Check size={12}/>Approve</button><button onClick={()=>void action(()=>api.rejectAutonomy(item.id),"Approval rejected.")}>Reject</button></p>}{item.status==="approved"&&<p><button onClick={()=>void action(()=>api.executeAutonomy(item.id),"Approved action executed and audited.")}><ShieldCheck size={12}/>Execute</button><button onClick={()=>void action(()=>api.revokeAutonomy(item.id),"Approval revoked before execution.")}>Revoke</button></p>}</div>)}</Audit>
      <Audit title="Autonomy audit" count={data?.autonomyAudit.length ?? 0}>{data?.autonomyAudit.slice(0,16).map(item=><div key={item.id}><strong>{item.category} · {item.action}</strong><span>{item.actor} · {formatDate(item.createdAt)}</span><small>{item.receiptHash.slice(0,16)}{item.sourceRunId?` · run ${item.sourceRunId.slice(0,8)}`:""}</small></div>)}</Audit>
      <Audit title="Recent bindings" count={data?.bindings.length ?? 0}>{data?.bindings.slice(0,12).map((item) => <div key={item.id}><strong>{item.applicationMode}</strong><span>{item.workflowId.slice(0,8)} · run {item.runId.slice(0,8)}</span><p>{(["adopted","partial","rejected"] as const).map(status=><button key={status} onClick={()=>void action(()=>api.setWorkflowApplication(item.id,status),`Binding marked ${status}.`)}>{status}</button>)}</p></div>)}</Audit>
      <Audit title="Learning policy" count={data?.learningPolicies.length ?? 0}>{data?.learningPolicies.slice(0,10).map(item=><div key={item.runId}><strong>{item.policy}</strong><span>run {item.runId.slice(0,8)} · {item.reason}</span><p>{(["allow","metadata_only","deny"] as const).map(policy=><button key={policy} onClick={()=>void action(()=>api.setLearningPolicy(item.runId,policy),`Learning policy set to ${policy}.`)}>{policy}</button>)}</p></div>)}</Audit>
      <Audit title="Quality" count={data?.quality.length ?? 0}>{data?.quality.map(item=><div key={item.workflowId}><strong>{Math.round(item.score*100)}%</strong><span>{item.samples} feedback sample(s) · {item.workflowId.slice(0,8)}</span></div>)}</Audit>
      <Audit title="Distillation jobs" count={data?.distillationJobs.length ?? 0}><p><span>{data?.distillationMetrics.queued??0} queued · {data?.distillationMetrics.running??0} running · {data?.distillationMetrics.deadLetter??0} dead letter</span></p>{data?.distillationJobs.slice(0,8).map(item=><div key={item.id}><strong>{item.status}</strong><span>{item.taskSignature} · {item.attempts} attempt(s){item.error?` · ${item.error}`:""}</span>{item.status==="dead_letter"&&<p><button onClick={()=>void action(()=>api.retryWorkflowDistillation(item.id),"Dead-letter job repaired and requeued.")}><RotateCcw size={12}/>Retry</button></p>}</div>)}</Audit>
      <Audit title="Canary traffic" count={data?.canaryBindings.length ?? 0}>{data?.canaryBindings.slice(0,10).map(item=><div key={item.id}><strong>{item.variant} · bucket {item.bucket}</strong><span>run {item.runId.slice(0,8)} · {item.outcomeStatus??"pending"}</span></div>)}</Audit>
      <Audit title="Evaluations" count={data?.evaluations.length ?? 0}>{data?.evaluations.slice(0,10).map(item=><div key={item.id}><strong>{item.kind} · {item.status}</strong><span>{item.sampleSize} samples · {Math.round(item.successRate*100)}% vs {Math.round(item.baselineRate*100)}% · {item.evaluatorId}@{item.evaluatorVersion}</span><small>{item.datasetId} · {item.receiptHash.slice(0,12)}</small></div>)}</Audit>
      <Audit title="Feedback" count={data?.feedback.length ?? 0}>{data?.feedback.slice(0,12).map((item) => <div key={item.id}><strong>{item.signal}</strong><span>{item.verified ? "verified" : "unverified"} · {item.note || "no note"}</span></div>)}</Audit>
      <Audit title="Revision proposals" count={data?.proposals.length ?? 0}>{data?.proposals.map((proposal) => <div key={proposal.id}><strong>{proposal.status}</strong><span>{proposal.reason}</span>{proposal.status === "candidate" && <p><button onClick={() => void action(() => api.approveWorkflowProposal(proposal.id), "Proposal approved.")}><Check size={12}/>Approve</button><button onClick={() => void action(() => api.rejectWorkflowProposal(proposal.id), "Proposal rejected.")}>Reject</button></p>}{proposal.status === "approved" && <p><button onClick={() => void action(() => api.requestWorkflowProposalApplication(proposal.id), "Application approval requested; proposal remains unapplied.")}><ShieldCheck size={12}/>Request apply</button></p>}</div>)}</Audit>
    </aside></div>
  </section></div>;
}

function WorkflowCard({ workflow, onAction }: { workflow: WorkflowDefinition; onAction: (work: () => Promise<unknown>, success: string) => Promise<void> }) {
  const deleted = Boolean(workflow.deletedAt); const revision = workflow.revision;
  return <article className={`learning-workflow ${deleted ? "deleted" : ""}`}><header><div><span className={`memory-kind ${workflow.status === "active" ? "fact" : "procedure"}`}>{deleted ? "tombstoned" : workflow.status}</span><strong>{revision?.name ?? workflow.id}</strong><small>revision {revision?.revision ?? "?"} · {revision?.riskClass ?? "unknown"} risk · {formatDate(workflow.updatedAt)}</small></div><div>{deleted ? <button onClick={() => void onAction(() => api.restoreWorkflow(workflow.id), "Workflow restored.")}><RotateCcw size={13}/>Restore</button> : <>{workflow.status !== "active" && revision?.riskClass !== "high" && <button onClick={() => void onAction(() => api.requestWorkflowActivation(workflow.id,revision?.id), "Activation approval requested; workflow remains inactive.")}><Check size={13}/>Request activation</button>}{workflow.status === "active" && <button onClick={() => void onAction(() => api.suspendWorkflow(workflow.id), "Workflow suspended.")}>Suspend</button>}<button className="memory-danger" onClick={() => void onAction(() => api.forgetWorkflow(workflow.id), "Workflow tombstoned with audit evidence retained.")}><Trash2 size={13}/>Forget</button></>}</div></header><p>{revision?.intent}</p><div className="memory-tags">{revision?.cueTerms.map((term) => <code key={term}>{term}</code>)}</div>{revision?.riskClass === "high" && <small className="audit-warn">High-risk workflows are hard-filtered from runtime recall and cannot use standard activation.</small>}</article>;
}
function Summary({icon,label,value,detail}:{icon:ReactNode;label:string;value:string;detail:string}){return <div className="autonomy-summary-card"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></div>}
function Audit({ title, count, children }: { title: string; count: number; children: ReactNode }) { return <section className="learning-audit-card"><div className="section-title"><span>{title}</span><small>{count}</small></div>{children || <p className="muted">No records.</p>}</section>; }
